# Generated by Django 4.2.6 on 2023-11-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='content_type',
        ),
        migrations.AddField(
            model_name='upload',
            name='content_type_pdf',
            field=models.CharField(default='application/pdf', max_length=200),
        ),
    ]
