# Generated by Django 4.2.6 on 2023-11-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_image_remove_upload_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='content_type_pdf',
            field=models.CharField(max_length=200),
        ),
    ]
