# Generated by Django 4.2.6 on 2023-11-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_upload_content_type_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='content_type_instrument',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='upload',
            name='content_type_midi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='upload',
            name='instrument',
            field=models.CharField(choices=[('violin', 'Violin'), ('viola', 'Viola'), ('cello', 'Cello'), ('flute', 'Flute'), ('clarinet', 'Clarinet'), ('oboe', 'Oboe')], default='violin', max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='midi',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='content_type_pdf',
            field=models.CharField(default='', max_length=200),
        ),
    ]
