# Generated by Django 4.2.6 on 2023-11-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_upload_content_type_instrument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='content_type_midi',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='content_type_pdf',
        ),
    ]
