# Generated by Django 4.2.6 on 2023-11-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_upload_content_type_midi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='content_type_instrument',
        ),
        migrations.AlterField(
            model_name='upload',
            name='instrument',
            field=models.CharField(choices=[('violin', 'Violin'), ('viola', 'Viola'), ('cello', 'Cello'), ('flute', 'Flute'), ('clarinet', 'Clarinet'), ('oboe', 'Oboe')], max_length=50),
        ),
    ]
