# Generated by Django 4.2.6 on 2023-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_upload_content_type_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='content_type_instrument',
            field=models.CharField(default='Violin', max_length=200),
        ),
    ]
