# Generated by Django 4.2.6 on 2023-11-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_upload_content_type_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='content_type_instrument',
        ),
    ]
